FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "HtmlPdfApi.csproj"
RUN dotnet build "HtmlPdfApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "HtmlPdfApi.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 5000
ENTRYPOINT ["dotnet", "HtmlPdfApi.dll"]