FROM mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR /src
COPY . .
RUN dotnet restore "HtmlPdfApi.csproj"
RUN dotnet build "HtmlPdfApi.csproj" -c Release -o /app/build
RUN dotnet publish "HtmlPdfApi.csproj" -c Release -o /app/publish